### PR TITLE
Basic layout

### PR DESCRIPTION
**Pull request by nathandcornell**
I think we're ready to merge this branch - anyone opposed?

### CODE REVIEW

**Comment by brooksn** [comment]
Looks great. I don't understand what placeForm and placeRequests are doing here. Also, the header image [isn't scaling quite the same way as the header text (gif)](http://brooksn.s3.amazonaws.com/ppf1.gif).

**Comment by nathandcornell** [comment]
The title scaling is fixed; not sure about placeForm and placeRequests. If those are no longer necessary you can delete them and commit to this branch before we merge.

**Comment by brooksn** [comment]
52f61bb looks like a work-in-progress by @abustamam for a different feature, but I don't think it matters to merge it. I'm okay with this pull request 👍 .

**Comment by abustamam** [comment]
@52f61bb was just me trying to get a datastructure to get all the PPIDs in
one place. Got close, but not close enough.

**Comment by nathandcornell** [comment]
So okay to merge with master?

**Comment by brooksn** [comment]
I think go ahead, it's been a couple of days.

**Pull request merged**
